version: '3.8'

services:
  hardhat:
    build:
      context: .
      dockerfile: Dockerfile.hardhat
    ports:
      - "8545:8545"
    networks:
      - halom-net

  updater:
    build:
      context: .
      dockerfile: Dockerfile.python
    env_file:
      - .env
    depends_on:
      - hardhat
    networks:
      - halom-net
    # The command will run the updater script in a loop,
    # simulating a cron job for local development.
    command: >
      sh -c "
        echo 'Waiting for Hardhat node to be available...' &&
        sleep 10 &&
        echo 'Deploying contracts...' &&
        npm run deploy:local &&
        echo 'Contracts deployed. Starting updater loop...' &&
        while true; do
          python3 -m offchain.updater;
          sleep 60;
        done
      "

networks:
  halom-net:
    driver: bridge 