# Use an official Node.js image to get build tools and npm
FROM node:18-alpine as builder

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .

# Use an official Python runtime as a parent image
FROM python:3.9-slim

WORKDIR /usr/src/app

# Install Python dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire app from the builder stage
COPY --from=builder /usr/src/app .

# The CMD is specified in the docker-compose.yml 